version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependencies-actions"
    reviewers:
      - "FabrizioCafolla"
  # @TODO: Add uv when it's available on Dependabot